import 'package:flutter/material.dart';
import '../models/market_listing.dart';
import '../models/listing_type.dart';

const sampleListings = [
  MarketListing(
    id: 'iphone14',
    type: ListingType.used,
    title: '아이폰 14 프로 256GB 딥퍼플',
    category: '디지털기기',
    price: '24,000 THB',
    place: '파타야',
    placeNote: '파타야 힐튼호텔 앞',
    postedAgo: '방금 전',
    sellerNickname: '하늘상점',
    tradeCount: 12,
    description:
        '한국에서 구매했고 케이스와 필름을 계속 사용했습니다. 배터리 성능 88%, 박스와 케이블 같이 드립니다. 직거래만 희망합니다.',
    icon: Icons.phone_iphone,
    color: Color(0xFF6750A4),
    photoCount: 5,
    contactNote: '카카오톡 ID 공개 가능',
    kakaoId: 'nproject_th',
    lineId: 'nproject.line',
    previousTrades: ['갤럭시 워치 5 판매 완료', '소니 헤드폰 거래 완료', '아이패드 미니 판매 완료'],
  ),
  MarketListing(
    id: 'membership',
    type: ListingType.used,
    title: '파타야 헬스장 회원권 2개월 양도',
    category: '기타 중고물품',
    price: '1,200 THB',
    place: '파타야',
    placeNote: '터미널21 근처 헬스장',
    postedAgo: '8분 전',
    sellerNickname: '운동하는곰',
    tradeCount: 4,
    description: '귀국 일정 때문에 남은 회원권을 양도합니다. 양도 가능 여부 확인 완료했습니다.',
    icon: Icons.card_membership,
    color: Color(0xFF455A64),
    photoCount: 2,
    previousTrades: ['요가매트 판매 완료', '러닝화 거래 완료'],
  ),
  MarketListing(
    id: 'delivery-request',
    type: ListingType.request,
    title: '서울에서 방콕 오시는 분, 영양제 부탁드려요',
    category: '해주세요',
    price: '수수료 700 THB 제안',
    place: '방콕',
    placeNote: '프롬퐁 BTS 근처',
    postedAgo: '31분 전',
    sellerNickname: '프롬퐁맘',
    tradeCount: 3,
    description:
        '서울 가족 집에 맡겨둔 작은 영양제 2통입니다. 무게 가볍고 포장 완료되어 있습니다. 방콕 도착 후 프롬퐁에서 받을 수 있어요.',
    icon: Icons.luggage_outlined,
    color: Color(0xFFE16A54),
    photoCount: 2,
    contactNote: '라인 ID로 연락 희망',
    lineId: 'prompong_mom',
    previousTrades: ['아기 옷 전달 요청 완료', '한국 과자 배송 요청 완료'],
  ),
  MarketListing(
    id: 'currency-baht',
    type: ListingType.currency,
    title: '남은 바트 3,200 THB를 원화로 교환 원해요',
    category: '화폐 교환',
    price: '3,200 THB',
    place: '치앙마이',
    placeNote: '님만해민 마야몰 1층',
    postedAgo: '1시간 전',
    sellerNickname: '치앙마이달',
    tradeCount: 5,
    description: '여행 후 남은 소액 바트입니다. 직접 만나서 금액 확인하고 서로 편한 기준으로 교환하고 싶습니다.',
    icon: Icons.payments_outlined,
    color: Color(0xFF2F80ED),
    photoCount: 1,
    kakaoId: 'chiangmai_moon',
    previousTrades: ['소액 바트 교환 완료', '한국 계좌 이체 거래 완료'],
  ),
  MarketListing(
    id: 'buy-iphone15',
    type: ListingType.used,
    tradeType: 'buy',
    title: '아이폰 15 Pro 256GB 삽니다',
    category: '디지털기기',
    price: '희망가 22,000 THB',
    place: '방콕',
    placeNote: '아속역 ~ 프롬퐁 가능',
    postedAgo: '12분 전',
    sellerNickname: '방콕라이프',
    tradeCount: 7,
    description: '블랙 또는 네이비 색상 희망합니다. 기능 이상 없는 제품이면 생활기스는 괜찮습니다.',
    icon: Icons.shopping_bag_outlined,
    color: Color(0xFFEF6C00),
    photoCount: 0,
    previousTrades: ['에어팟 프로 구매 완료', '아이패드 거래 완료'],
  ),
];
