// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-YthDzO64YBukHy7iRIHSYiPOJiA1QBc',
    appId: '1:400795002326:web:bbfdb1c8850384148eb077',
    messagingSenderId: '400795002326',
    projectId: 'nproject-302c9',
    authDomain: 'nproject-302c9.firebaseapp.com',
    storageBucket: 'nproject-302c9.firebasestorage.app',
    measurementId: 'G-SPZQ6LRL9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1o8K3gWB__bUfWVa-la5ovGVgTzc02Cg',
    appId: '1:400795002326:android:701bbf9a5cfb041c8eb077',
    messagingSenderId: '400795002326',
    projectId: 'nproject-302c9',
    storageBucket: 'nproject-302c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD219x6dbt5ZItMz7DTnw7hQpdC5XpGhXo',
    appId: '1:400795002326:ios:41776c79599baede8eb077',
    messagingSenderId: '400795002326',
    projectId: 'nproject-302c9',
    storageBucket: 'nproject-302c9.firebasestorage.app',
    iosBundleId: 'com.nproject.nproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD219x6dbt5ZItMz7DTnw7hQpdC5XpGhXo',
    appId: '1:400795002326:ios:41776c79599baede8eb077',
    messagingSenderId: '400795002326',
    projectId: 'nproject-302c9',
    storageBucket: 'nproject-302c9.firebasestorage.app',
    iosBundleId: 'com.nproject.nproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-YthDzO64YBukHy7iRIHSYiPOJiA1QBc',
    appId: '1:400795002326:web:a8727c04d07a2d6b8eb077',
    messagingSenderId: '400795002326',
    projectId: 'nproject-302c9',
    authDomain: 'nproject-302c9.firebaseapp.com',
    storageBucket: 'nproject-302c9.firebasestorage.app',
    measurementId: 'G-HTZDCC2KR7',
  );
}
